name: Hostinger Deployment Workflow

on:
  push:
    branches:
        - master
        - release/*
        - 'feature/**'
        - 'feature/pasarela-pagos'
        - 'feature/suscripciones'
        - 'feature/notificaciones-push'
        - 'feature/notificaciones-push-backend'
        - 'feature/apis-logica-negocio'
        - 'feature/diseno-responsivo'
        - 'feature/offline-pwa'
jobs:
  deploy-to-hostinger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to Hostinger
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
            ncftpput -R -v -u "$FTP_USERNAME" -p "$FTP_PASSWORD" "$FTP_HOST" /public_robe/ build/*
